{% set name = "flytekitplugins-sqlalchemy" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flytekitplugins-sqlalchemy-{{ version }}.tar.gz
  sha256: dbf8ce1789f47edb957870e700840e22917664aac693c98d230fa2498f0a6b80

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - flytekit >=1.0.0b3,<1.2.0
    - sqlalchemy >=1.4.7

test:
  imports:
    - flytekitplugins.sqlalchemy
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/flytekitplugins-sqlalchemy/
  summary: SQLAlchemy plugin for flytekit
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  description: |
    SQLAlchemy plugin for Flytekit: `{{ name }}`

    PyPI: [https://pypi.org/project/flytekitplugins-sqlalchemy/](https://pypi.org/project/flytekitplugins-sqlalchemy/)

  doc_url: https://github.com/flyteorg/flytekit/tree/master/plugins
  dev_url: https://github.com/flyteorg/flytekit/tree/master/plugins/flytekit-sqlalchemy

extra:
  recipe-maintainers:
    - sugatoray
